services:
  webinteract-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webinteract-mcp-server
    ports:
      - "8080:8080"
    environment:
      # ASP.NET Core Configuration
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      
      # McpInteract Tool Configuration
      - McpInteract__Tool__TimeoutMinutes=5
      - McpInteract__Tool__EnableDetailedErrorLogging=false
      
      # McpInteract CORS Configuration
      - McpInteract__Cors__AllowAnyOrigin=true
      
      # Logging Configuration
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__WebInteractMCPServer=Information
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD-SHELL", "timeout 3s bash -c '</dev/tcp/localhost/8080' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # depends_on:
    #   - redis

  # Optional Redis service for caching and SignalR backplane. TODO: Doesn't support Redis Backplane yet to scale out
  # redis:
  #   image: redis:7-alpine
  #   container_name: webinteract-redis
  #   ports:
  #     - "6379:6379"
  #   command: redis-server --appendonly yes
  #   volumes:
  #     - redis-data:/data
  #   networks:
  #     - webinteract-network
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3

# volumes:
#   redis-data:
#     driver: local
