services:
  webinteract-mcp-server:
    image: vijaynirmalpon/web-interact-mcp-server:latest
    container_name: webinteract-mcp-server-published
    ports:
      - "8080:8080"
    environment:
      # ASP.NET Core Configuration
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      
      # McpInteract Tool Configuration
      - McpInteract__Tool__TimeoutMinutes=5
      - McpInteract__Tool__EnableDetailedErrorLogging=false
      
      # McpInteract CORS Configuration
      - McpInteract__Cors__AllowAnyOrigin=true
      
      # Logging Configuration
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__WebInteractMCPServer=Information
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD-SHELL", "timeout 3s bash -c '</dev/tcp/localhost/8080' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Alternative preview version
  # webinteract-mcp-server-preview:
  #   image: vijaynirmalpon/web-interact-mcp-server:preview
  #   container_name: webinteract-mcp-server-preview
  #   ports:
  #     - "8081:8080"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - McpInteract__Tool__EnableDetailedErrorLogging=true
  #     - McpInteract__Cors__AllowAnyOrigin=true
  #   restart: unless-stopped
