services:
  webintract-mcp-server:
    image: vijaynirmalpon/web-intract-mcp-server:latest
    container_name: webintract-mcp-server-published
    ports:
      - "8080:8080"
    environment:
      # ASP.NET Core Configuration
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      
      # McpIntract Tool Configuration
      - McpIntract__Tool__TimeoutMinutes=5
      - McpIntract__Tool__EnableDetailedErrorLogging=false
      
      # McpIntract CORS Configuration
      - McpIntract__Cors__AllowAnyOrigin=true
      
      # Logging Configuration
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__WebIntractMCPServer=Information
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD-SHELL", "timeout 3s bash -c '</dev/tcp/localhost/8080' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Alternative preview version
  # webintract-mcp-server-preview:
  #   image: vijaynirmalpon/web-intract-mcp-server:preview
  #   container_name: webintract-mcp-server-preview
  #   ports:
  #     - "8081:8080"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - McpIntract__Tool__EnableDetailedErrorLogging=true
  #     - McpIntract__Cors__AllowAnyOrigin=true
  #   restart: unless-stopped
